from .settings import (
    PROJECT_ROOT,

    MODELS_DIR,
    DATA_DIR,
    OUTPUTS_DIR,
    REPORTS_DIR,
    INSPECTIONS_DIR,

    CLASSIFICATION_MODELS_DIR,
    DETECTION_MODELS_DIR,
    DAMAGE_MODELS_DIR,
    VEHICLE_DAMAGE_SEGMENTER_DIR,
    VEHICLE_PART_SEGMENTER_DIR,
    VIEW_CLASSIFIER_DIR,

    YOLO_DETECTOR_MODEL,
    YOLO_DETECTOR_LARGE_MODEL,

    VIEW_CLASSIFIER_MODEL,
    YOLO_CLASSIFIER_BASE,

    DAMAGE_MODEL_PATH,

    VEHICLE_PART_MODEL_PATH,
    VEHICLE_PART_MODEL_LAST_PATH,

    FRAME_SKIP,

    VEHICLE_DETECTION_CONFIDENCE,
    VEHICLE_PART_CONFIDENCE,
    DAMAGE_CONFIDENCE,
    VIEW_CLASSIFICATION_CONFIDENCE,

    INSPECTION_OUTPUT_DIR,

    VEHICLE_DETECTOR_MODEL,
    VEHICLE_VIEW_CLASSIFIER_MODEL,
    VEHICLE_PART_SEGMENTER_MODEL,
    VEHICLE_DAMAGE_MODEL,

    ensure_project_directories,
    verify_model_files,
    get_config_summary,
)
